[FE] React Query 도입
christmas-tree-map/christmas-tree-map pull request #22
Opened 2024-12-03 08:28 UTC by chosim-dvlpr

## 연관된 이슈
- close #20 
## 구현한 기능
- React Query 도입 및 초기 세팅
- 기존 api React Query로 변경

### 구현한 내용
- React Query와 devtools를 설치했습니다.
- 구현 편의를 위해 `staleTime`과 `gcTime`은 주석처리해두었습니다.
```tsx
export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      throwOnError: true,
      // staleTime: 1000 * 60 * 5, // 개발 편의를 위해 주석처리합니다.
      // gcTime: 1000 * 60 * 10, // 개발 편의를 위해 주석처리합니다.
    },
  },
});
```

- 기존 api 함수를 사용하는 곳에 custom hook을 적용하여 React Query로 변경하였습니다.
```tsx
const useFeeds = () => {
  const { data, ...rest } = useQuery({
    queryKey: [FEED_KEYS.FEEDS],
    queryFn: () => getFeeds(),
  });

  return { feeds: data ?? [], ...rest };
};
```

```tsx
  const { mutate: addFeedMutation } = useMutation({
    mutationFn: postFeed,
    onSuccess: () => queryClient.invalidateQueries({ queryKey: [FEED_KEYS.FEEDS] }),
  });

  return { addFeedMutation };
};
```

- Query key를 분리했습니다. 관심사에 따라 `FEED_KEYS`로 네이밍했는데 좋은 의견 있으면 알려주세요!
```tsx
export const FEED_KEYS = {
  FEEDS: 'feeds',
};
```

2024-12-03 10:51 UTC, anttiey requested changes
`devtools` 까지! 너무 좋습니다 👍 일부 코드에서 컨벤션과 다른 부분이 있어서 코멘트 남겼어요 🙇🏻‍♀️

2024-12-03 10:51 UTC, anttiey commented on frontend/src/apis/feed.ts
>  export const getFeeds = async () => {
```suggestion
export const getFeeds = async (): Promise<Feeds[]> => {
```

위와 같이 표현하면 타입 단언을 쓰지 않고도 `data` 의 타입을 명시할 수 있을 거 같은데 혹시 타입 단언을 사용한 이유가 있을까요?

2024-12-03 10:51 UTC, anttiey commented on frontend/src/hooks/Feed/useFeeds.ts
> +const useFeeds = () => {
`데이터를 가져오는 GET 요청일 경우 use*-Query 와 같이 네이밍된 파일 아래에 위치합니다.` 라는 컨벤션이 있어서 `useFeedsQuery` 와 같이 네이밍하면 좋을 거 같아요 😆

2024-12-03 10:51 UTC, anttiey commented on frontend/src/hooks/Feed/useFeedMutation.ts
> +import { queryClient } from '@/main';
쿼리 훅의 경우 `queries` 폴더 안에 두기로 했었는데 `hooks` 폴더 안에 들어가 있어서 확인 부탁드릴게요 🙌🏻

2024-12-03 10:51 UTC, anttiey commented on frontend/src/main.tsx
> +      <QueryClientProvider client={queryClient}>
👍👍👍

2024-12-03 11:06 UTC, anttiey commented on frontend/src/apis/feed.ts
>  export const getFeeds = async () => {
```jsx
export const getFeeds = async (): Promise<Feeds[]> => {
  return await requestAPI.get('/feeds');
};
```

제가 다시 확인해 보니까 함수를 이렇게 쓰지 않으면 타입 추론이 안 되는 군요 🥹 개인적으로 타입 단언을 사용하면 타입 체크가 불가능하기 때문에 타입 선언으로 표현하는 게 좋을 거 같아서 한번 방법을 찾아 보겠습니다!

2024-12-03 11:31 UTC, anttiey commented on frontend/src/apis/feed.ts
>  export const getFeeds = async () => {
```jsx
const apiMethods = async <T>({ method, endpoint, body }: ApiMethodsProps): Promise<T> => {
 ///
}

const requestAPI = {
  get: <T>(endpoint: string): Promise<T> => apiMethods({ method: 'GET', endpoint }),
 ///
}

export const getFeeds = async () => {
  const { data } = await requestAPI.get<{ data: Feeds[] }>('/feeds');
  return data;
};
```

만약 타입 단언을 쓰지 않는다면 위와 같이 제네릭으로 표현하는 방법이 있을 거 같은데 프룬은 어떤 방법이 낫다고 생각하시나요?

2024-12-03 12:48 UTC, chosim-dvlpr commented on frontend/src/apis/feed.ts
>  export const getFeeds = async () => {
타입 단언보다 제네릭을 사용하는 방법이 더 좋을 것 같아요! 짚어주셔서 감사해요😚

2024-12-03 13:28 UTC, chosim-dvlpr commented on frontend/src/hooks/Feed/useFeeds.ts
> +const useFeeds = () => {
으악 감사해요!

2024-12-03 13:33 UTC, chosim-dvlpr commented on frontend/src/apis/feed.ts
>  export const getFeeds = async () => {
제안해주신 제네릭이 더 적절할 것 같아서 리팩토링을 진행했습니다! 추가적으로 구조상 변경이 있었는데요, 제네릭을 추가하는 경우 아래와 같이 가독성이 좋지 않아서 `requestAPI` 내부에서 `apiMethods`, `get`, `post` 등의 http method를 호출하는 방식으로 개선했습니다.

```tsx
  get: <T>(endpoint: string): Promise<T> => apiMethods<T>({ method: 'GET', endpoint }),
  post: <T>(endpoint: string, body: Record<string, any>): Promise<T> =>
    apiMethods<T>({ method: 'POST', endpoint, body }),
  patch: <T>(endpoint: string, body: Record<string, any>): Promise<T> =>
    apiMethods<T>({ method: 'PATCH', endpoint, body }),
  delete: (endpoint: string): Promise<void> => apiMethods({ method: 'DELETE', endpoint })
```

```tsx
const requestAPI = {
  async apiMethods<T>({ method, endpoint, body }: ApiMethodsProps): Promise<T> {
    // ...
  },

  get<T>(endpoint: string): Promise<T> {
    return this.apiMethods<T>({ method: 'GET', endpoint });
  },
  // ...
}
```

2024-12-03 13:36 UTC, chosim-dvlpr commented on frontend/src/apis/feed.ts
>  export const getFeeds = async () => {
[a66d63f](https://github.com/christmas-tree-map/christmas-tree-map/pull/22/commits/a66d63f257266723990a5439d52f9555f99d2445)

2024-12-04 08:54 UTC, anttiey approved these changes

2024-12-04 08:54 UTC, anttiey commented on frontend/src/apis/feed.ts
>  export const getFeeds = async () => {
제 생각에도 body 타입을 좁힌다면 `Record<string, any>` 가 최선일 것 같습니다 🥲 리팩토링한 코드 너무 좋네요 👏

2024-12-04 11:03 UTC, merged