[FE] FloatingButton 구현
christmas-tree-map/christmas-tree-map pull request #27
Opened 2024-12-03 12:00 UTC by anttiey

# 연관된 이슈
- closes: #15 

# 구현한 기능
- [x] FloatingButton 컴포넌트 구현
- [x] FloatingButton 컴포넌트 적용

# 구현한 내용
- 기존에 있던 FloatingButton 컴포넌트를 피그마 디자인으로 변경했습니다.
- 지도 페이지에서 컴포넌트를 확인할 수 있도록 코드를 변경했습니다.
- 제출 페이지에서는 컴포넌트가 표시되지 않도록 `location.pathname` 으로 조건부 렌더링을 걸어 두었습니다.

2024-12-03 13:55 UTC, chosim-dvlpr requested changes
깔끔하게 작성해 주셔서 확인하기 편했어요 파슬리~!! 사소하지만 type 관련 코멘트 달아놓았습니다 ㅎㅎ
확인하시고 다시 요청 주세요 :)

2024-12-03 13:55 UTC, chosim-dvlpr commented on frontend/src/components/_common/FloatingButton/FloatingButton.tsx
> +const FloatingButton = ({ onClick }: FloatingButtonProps) => {
`ButtonHTMLAttributes`을 타입으로 지정해서 `onClick` props를 타입에 추가하지 않아도 될 것 같은데 아래 방법은 어떨까요??

```tsx
const FloatingButton = ({ onClick }: React.ButtonHTMLAttributes<HTMLButtonElement>) => {
  // ...
}

2024-12-03 13:55 UTC, chosim-dvlpr commented on frontend/src/pages/TreeMap/TreeMap.tsx
> +      {location.pathname !== '/submit' && <FloatingButton onClick={handleButtonClick} />}
오오 이런 방법이 있군요!👍🏻👍🏻

2024-12-04 09:27 UTC, anttiey commented on frontend/src/components/_common/FloatingButton/FloatingButton.tsx
> +const FloatingButton = ({ onClick }: FloatingButtonProps) => {
`ButtonHTMLAttributes` 를 사용하도록 반영했습니다 ☺️

2024-12-04 11:11 UTC, chosim-dvlpr approved these changes
고생하셨습니다~~~~~!!!🎄🚀

2024-12-04 13:53 UTC, merged