[FE] Header, NavBar 구현
christmas-tree-map/christmas-tree-map pull request #30
Opened 2024-12-11 07:12 UTC by anttiey

# 연관된 이슈
- closes: #16 
- closes: #17 

# 구현한 기능
- [x] Header 컴포넌트 구현
- [x] NavBar 컴포넌트 구현

# 구현한 내용
- 아이콘 적용을 위해 `react-icons/all-files` 라이브러리를 설치했습니다.

# 궁금한 사항
- 피그마에 구현된 디자인을 반영하다 궁금한 사항이 생겨 질문드립니다! 🥹

> Header
![스크린샷 2024-12-11 오후 4 19 33](https://github.com/user-attachments/assets/0fc3003b-1ed3-43a0-b879-868b88aeaa63)

> NavBar
![스크린샷 2024-12-11 오후 4 18 04](https://github.com/user-attachments/assets/e9818863-c2d9-4648-a367-0a2b8aa8164b)

1. `Header` 와 `NavBar` 의 높이가 다른 이유가 있나요? (`Header` 의 경우 48px, `NavBar` 의 경우 네비게이션 바만 따졌을 때 49px)
2. `Header` 와 `NavBar` 의 좌우 여백이 다른 이유가 있나요? (`Header` 의 경우 16px, `NavBar` 의 경우 20px)
3. `NavBar` 에서 실질적인 네비게이션 바 영역을 제외하고, 하단 빈 공간이 34px이 아닌 43px인 이유가 있나요?

2024-12-11 14:23 UTC, chosim-dvlpr commented
앗🥲 미안해요 파슬리... 수정된 버전은 `NavBar` 높이 58px, margin 16px 0, margin-bottom 34px입니다.

> 1. Header 와 NavBar 의 높이가 다른 이유가 있나요? (Header 의 경우 48px, NavBar 의 경우 네비게이션 바만 따졌을 때 49px)
디자인 가이드 기준으로 `Header`의 세로 길이는 최소 44px, `NavBar`의 세로 길이는 최소 50px이라고 합니다. `NavBar`에서 사용자에게 보여주어야 할 양이 많다 보니 `NavBar`의 높이를 더 높게 설정하도록 가이드를 지정한 것 같아요.

좌우 여백도 16px로 맞추었어요 번거롭게 해서 미안해요🥲

2024-12-11 14:28 UTC, chosim-dvlpr requested changes

2024-12-11 14:28 UTC, chosim-dvlpr commented on frontend/src/assets/tree-icon.png
`react-icons`에서 에셋을 [여기서](https://react-icons.github.io/react-icons/search/#q=christ) `TbChristmasTree `으로 대신하는 건 어떨까요??

2024-12-11 14:28 UTC, chosim-dvlpr commented on frontend/src/components/_common/NavBar/NavBar.tsx
> +        </Link>
👍🏻👍🏻

2024-12-12 06:49 UTC, anttiey commented on frontend/src/assets/tree-icon.png
제가 에셋을 `react-icons` 에 있는 것으로 대체하려고 했는데 트리 에셋들의 경우 `react-icons/all-files` 라이브러리에는 없더라고요 🥲 [트리 아이콘 목록](https://react-icons.github.io/react-icons/search/#q=tree)에서 있는 게 `FaTree` 뿐인데 이 아이콘은 본래 디자인이랑은 조금 달라서 프룬은 어떻게 생각하시나요?

2024-12-12 08:01 UTC, chosim-dvlpr commented on frontend/src/assets/tree-icon.png
허거덩...그렇군요..! 아이콘 찾어봤더니 fa6 FaTree 괜찮아 보이네요! 피그마 디자인도 함께 수정해놓겠습니다 :)

2024-12-12 12:43 UTC, anttiey commented on frontend/src/assets/tree-icon.png
> <img width="1031" alt="스크린샷 2024-12-12 오후 9 40 51" src="https://github.com/user-attachments/assets/a4f77183-ad72-433c-ba1b-7ca0962baa5e" />

해당 아이콘도 없어서 `fa FaTree` 로 반영했습니다!

2024-12-12 12:53 UTC, chosim-dvlpr approved these changes
고생하셨습니다 파슬리~!!🪴✨✨

2024-12-12 12:53 UTC, chosim-dvlpr commented on frontend/src/components/_common/NavBar/NavBar.css.ts
> +  }
👍🏻

2024-12-13 13:08 UTC, merged