[FE] 랜딩 페이지 구현 #34
christmas-tree-map/christmas-tree-map pull request #55
Opened 2024-12-19 09:40 UTC by anttiey

2024-12-19 17:37 UTC, chosim-dvlpr requested changes
디자인 너무 깜찍하고 귀여워요,,😍 

> 아래 공백을 채우기 위해서 5초 만에 로그인하고 시작하기 버튼을 넣어 두었는데, 더 좋은 아이디어가 있으면 추천해 주세요 😅

메리 트리스마스와 함께~ 부분을 `Circle` 아래쪽에 배치하고, 여백을 의도적으로 많이 남기는 것은 어떨까요? `시작하기` 버튼 위치는 그대로 두고요!

> 아무래도 세부적인 디자인이 들어가다 보니 모바일 화면에만 호환되는데 (가로 길이 500px 을 넘어가는 경우 디자인이 깨짐) 기본적으로 모바일 화면에 맞춰지도록 화면 비율을 조정하는 것은 어떨까요?

오 좋습니다! 모바일 최대 너비인 480px를 메인 컨텐츠의 최대 너비로 지정하고 최소 너비는 갤럭시 폴드를 접었을 때를 기준으로 320px은 어떨까요?

2024-12-19 17:37 UTC, chosim-dvlpr commented on frontend/src/components/_common/Button/Button.css.ts
> +  disabled: [Base, { color: vars.colors.white, background: vars.colors.grey[500] }],
disabled 시 cursor를 `default`로 하는 것은 어떨까요?!

2024-12-19 17:37 UTC, chosim-dvlpr commented on frontend/src/pages/Landing/Landing.css.ts
> +globalStyle(`${TitleContainer} span`, { opacity: 0.6 });
오오 이런 방법도 있군요!🤩

2024-12-19 17:37 UTC, chosim-dvlpr commented on frontend/src/pages/Landing/Landing.tsx
> +          </Button>
추후 로그인 기능이 들어오면 이 코드를 추가하는 것은 어떨까요~? 지금은 주석처리하구요!

2024-12-20 08:35 UTC, anttiey commented on frontend/src/components/_common/Button/Button.css.ts
> +  disabled: [Base, { color: vars.colors.white, background: vars.colors.grey[500] }],
`cursor: not-allowed` 로 지정해 봤는데 프룬의 의견이 궁금합니다!

2024-12-20 08:40 UTC, anttiey commented
## 🛠️ 코멘트 반영 사항
- [x] 최소 너비를 `320px`, 최대 너비를 `480px` 로 잡고 기본적으로 컨텐츠의 너비가 모바일에 호환되도록 변경했습니다. 제가 최대한 모두 반영하려고 했는데 디자인이 깨지는 부분이 있다면 알려 주세요 🥹
- [x] 버튼의 `disabled` 상태를 스토리북에 추가했습니다!

2024-12-20 10:47 UTC, chosim-dvlpr commented on frontend/src/components/_common/Button/Button.css.ts
> +  disabled: [Base, { color: vars.colors.white, background: vars.colors.grey[500] }],
`not-allowed`도 확실하게 알려줄 수 있어서 좋을 것 같아요!

2024-12-20 10:51 UTC, chosim-dvlpr approved these changes
고생하셨습니다 파슬리~!! 디자인도 깨지는 부분이 없는지 확인했습니다 ㅎㅎ 눈사람 쏘큩,,,☃️🩵 approve 할게용!

2024-12-20 12:57 UTC, merged